# Generated by Django 2.2.3 on 2019-07-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cash',
            field=models.IntegerField(default=1000),
        ),
    ]
