# Generated by Django 2.2.3 on 2019-08-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_player_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='can_make_money',
            field=models.BooleanField(default=False),
        ),
    ]
